### ISSUE TITLE
Reference 1 on MPO page has truncated author name

### ISSUE THREAD

**Issue by jiahao** [TensorNetwork/tensornetwork.org#11]
The page at http://tensornetwork.org/mpo/ currently renders the first reference as

<img width="900" alt="Screen Shot 2020-04-10 at 5 00 26 PM" src="https://user-images.githubusercontent.com/1732/79022842-dd5fde80-7b4c-11ea-99cd-ae2d575c8e38.png">

The last name of the last author appears to be truncated.

**Comment by emstoudenmire** [comment]
Thanks for catching this!
