### ISSUE TITLE
TeNeS

### ISSUE THREAD

**Issue by takeokato719** [TensorNetwork/tensornetwork.org#17]
The team at my institute developed TeNeS, software for tensor network calculation of lattice models.

https://github.com/issp-center-dev/TeNeS

I am glad if you add this software to the following list:

https://tensornetwork.org/software/

**Comment by emstoudenmire** [comment]
Great - thanks for letting me know about this. Would you be willing to make a pull request that updates that page? All of the source code of tensornetwork.org is plain Markdown files so it should be easy to modify that page to include your software.

Here is the link to the relevant source file: https://github.com/TensorNetwork/tensornetwork.org/blob/master/src/software/index.md

**Comment by takeokato719** [comment]
Thanks! Wait for a while, please.

**Comment by emstoudenmire** [comment]
Great - no problem

**Comment by TsuyoshiOkubo** [comment]
I made a pull request on this issue. 
Could you please check it?

**Comment by emstoudenmire** [comment]
Thank you for the reminder! I just merged your PR. Appreciate you taking the time to help me with the content.
