### ISSUE TITLE
TDVP: equation doesn't render

### ISSUE THREAD

**Issue by DerWeh** [TensorNetwork/tensornetwork.org#19]
The `alignat` environment in https://tensornetwork.org/mps/algorithms/timeevo/tdvp.html is not rendered.

**Comment by emstoudenmire** [comment]
Thanks for pointing this out! I just pushed a change that should fix this now. Please let me know if you see anything else wrong with that page.

**Comment by haiyongsong1921** [comment]
This issue still exist.
