### ISSUE TITLE
This issue still exist.

### ISSUE THREAD

**Issue by haiyongsong1921** [TensorNetwork/tensornetwork.org#23]
This issue still exist.

_Originally posted by @haiyongsong1921 in https://github.com/TensorNetwork/tensornetwork.org/issues/19#issuecomment-1206171525_

**Comment by emstoudenmire** [comment]
Could you please clarify what issue you are referring to?

**Comment by haiyongsong1921** [comment]
It works when I switch Chrome to Safari, I will close this.
