### ISSUE TITLE
Add torchTT to the list of Software

### ISSUE THREAD

**Issue by MazenAli** [TensorNetwork/tensornetwork.org#37]
Add torchTT to the list of "High-Level Tensor Software".

Link to repo: https://github.com/ion-g-ion/torchTT/tree/main

Similar to ttpy: https://github.com/oseledets/ttpy (maybe also add it)
Which in turn is based on: https://github.com/oseledets/TT-Toolbox

But with added torch AD functionality.

**Comment by emstoudenmire** [comment]
Thanks! Just added it.
