### ISSUE TITLE
Tensor diagram notation graphics

### ISSUE THREAD

**Issue by stared** [TensorNetwork/tensornetwork.org#4]
How did you create these diagrams?

I did create some (e.g. the one in [Matrix product state](https://en.wikipedia.org/wiki/Matrix_product_state) Wikipedia page; I did my PhD in quantum physics), but nothing nearly as visually pleasing. 
I've found them nice (vide https://medium.com/@pmigdal/in-the-topic-of-diagrams-i-did-write-a-review-simple-diagrams-of-convoluted-neural-networks-6418a63f9281). 

Moreover, I write "thinking in tensors, writing in PyTorch" and want to introduce a (technical) general audience to these diagrams. Such diagrams (also with examples from other disciplines), would be useful... and visually pleasing.

**Comment by emstoudenmire** [comment]
Hi, good question, although you may be disappointed with the answer. So far I've just been creating the diagrams in Apple Keynote. I'm glad you like the style; it's just a drawing style I developed after working with this notation for quite a while.

I'd be happy to post or send you the Keynote file containing the graphics from the tensornetwork.org site if you want to use it as sort of a template for making your own (assuming you have a Mac!). 

My colleagues at Flatiron Institute and I are pursuring hiring someone to make software for drawing these diagrams, and for converting diagrams into code that can actually be run (in various tensor network software libraries). 

I really like the idea of using this notation in other fields; for example, I taught myself how kernel learning (SVM theory) works by writing out the equations diagrammatically, and it was very helpful.
